# Generated by Django 2.2.2 on 2019-06-30 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=0, max_digits=3)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(default='', max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=120)),
                ('last_name', models.CharField(default='', max_length=120)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('contact_no', models.CharField(default='', max_length=20)),
                ('order_id', models.CharField(blank=True, default='', max_length=240, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
