# Generated by Django 2.2.2 on 2019-06-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_Status',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_Txt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
