# Generated by Django 2.2.2 on 2019-06-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190630_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='order_Txt',
            new_name='order_TxTime',
        ),
    ]
