# Generated by Django 2.2.2 on 2019-07-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190630_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
