# Generated by Django 2.2.2 on 2019-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_plan',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
